apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangulpangpang-frontend-deployment
  namespace: dev
  labels:
    app: hangulpangpang-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangulpangpang-frontend
  template:
    metadata:
      labels:
        app: hangulpangpang-frontend
    spec:
      containers:
      - name: hangulpangpang-frontend-container
        image: ghcr.io/tiny-solver/hangulpangpang-frontend:latest
        ports:
        - containerPort: 4173
      imagePullSecrets:
      - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: hangulpangpang-frontend-service
  namespace: dev
spec:
  selector:
    app: hangulpangpang-frontend
  ports:
    - protocol: TCP
      port: 4173
      targetPort: 4173
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hangulpangpang-frontend-ingress
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  tls:
  - hosts:
    - '*.choigawoon.site'
    secretName: choigawoon-site-tls
  rules:
  - host: hangulpangpang.choigawoon.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hangulpangpang-frontend-service
            port:
              number: 4173
