name: Docker Compose Build on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the current tag
      id: vars
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Get short SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker images
      run: |
        IMAGE_TAG="${TAG_NAME}-${SHORT_SHA}"
        docker-compose -f docker-compose.yml build
        docker tag ghcr.io/tiny-solver/hangulpangpang-frontend:latest ghcr.io/tiny-solver/hangulpangpang-frontend:${IMAGE_TAG}
        docker push ghcr.io/tiny-solver/hangulpangpang-frontend:${IMAGE_TAG}
